### ISSUE TITLE
prefers-color-scheme

### ISSUE THREAD

**Issue by wen403** [uni-helper/vitesse-uni-app#13]
### 描述问题

请问在代码中我怎么才能设置默认亮色主题？或者将其移除。

### 复现

![image](https://github.com/uni-helper/vitesse-uni-app/assets/67454874/50319450-c1ba-4fd1-bd65-4f76309c7dc1)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 1.87 GB / 15.92 GB
  Binaries:
    Node: 16.13.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 8.1.0 - D:\nodejs\npm.CMD
    pnpm: 8.0.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

pnpm

### 核对

- [x] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。

**Comment by wen403** [comment]
![Uploading image.png…]()

**Comment by yun8711** [comment]
这个配置应该写在哪里，具体哪个配置文件中？

**Comment by yun8711** [comment]
> ![image](https://private-user-images.githubusercontent.com/67454874/256095926-884c96cd-1ee7-4127-947e-86bfcd1c52cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODA2MjQsIm5iZiI6MTcxNzM4MDMyNCwicGF0aCI6Ii82NzQ1NDg3NC8yNTYwOTU5MjYtODg0Yzk2Y2QtMWVlNy00MTI3LTk0N2UtODZiZmNkMWM1MmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAyMDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTY0NTc3NjhjYzkyMDYyMzNiMTYyMmViYmVmMDU1MzQ1Mjc4N2M0ZmI5ZTI3NTY5Njk4NzM4ZTg5MmI0MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Z59RG9gqy-xw9nABgK_qVmjE5mtZrgRYAdJIitc2n4)

这个配置应该写在哪里，具体哪个配置文件中？

**Comment by yun8711** [comment]
> > ![image](https://private-user-images.githubusercontent.com/67454874/256095926-884c96cd-1ee7-4127-947e-86bfcd1c52cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODA2MjQsIm5iZiI6MTcxNzM4MDMyNCwicGF0aCI6Ii82NzQ1NDg3NC8yNTYwOTU5MjYtODg0Yzk2Y2QtMWVlNy00MTI3LTk0N2UtODZiZmNkMWM1MmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAyMDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTY0NTc3NjhjYzkyMDYyMzNiMTYyMmViYmVmMDU1MzQ1Mjc4N2M0ZmI5ZTI3NTY5Njk4NzM4ZTg5MmI0MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Z59RG9gqy-xw9nABgK_qVmjE5mtZrgRYAdJIitc2n4)
> 
> 这个配置应该写在哪里，具体哪个配置文件中？

找到了，在 manifest.confit.ts 中配置
