### ISSUE TITLE
如何在setup 外部使用 route

### ISSUE THREAD

**Issue by Abernethy-BY** [uni-helper/vitesse-uni-app#14]
### 描述问题

我遇到一个问题
要在 https 请求时，如果遇到token过期的情况，我需要在 请求结束后 重定向到 login 页，我希望在ts文件中写成通用的方法，但是当前的架构没有导出route对象

### 复现

https://github.com/HW-maintenance/HW_maintenance_app.git

### 系统信息

```Shell
环境：微信开发工具
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
当然是直接用uni的api鸭

**Comment by Abernethy-BY** [comment]
啊，uni的api，emm

**Comment by KeJunMao** [comment]
https://uniapp.dcloud.net.cn/api/router.html#
