### ISSUE TITLE
 ReferenceError: process is not defined

### ISSUE THREAD

**Issue by tanwenchao** [uni-helper/vitesse-uni-app#21]
### 描述问题

运行 dev:mp-weixin在微信小程序，报错ReferenceError: process is not defined

### 复现

 ReferenceError: process is not defined

### 系统信息

```Shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 37.89 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 14.1.2
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by tanwenchao** [comment]
<img width="802" alt="image" src="https://github.com/uni-helper/vitesse-uni-app/assets/17673324/1b39345a-2372-499f-b86a-fe423135eeb2">

**Comment by tanwenchao** [comment]
<img width="841" alt="image" src="https://github.com/uni-helper/vitesse-uni-app/assets/17673324/7bd4c9fe-b5e1-433a-8c3a-102adcd9fb4d">

**Comment by KeJunMao** [comment]
不是本模板的问题~

似乎是你或者你引用的其他库导入了 babel-type
