### ISSUE TITLE
建议使用 .gitignore 忽略由插件生成的文件

### ISSUE THREAD

**Issue by DevDengChao** [uni-helper/vitesse-uni-app#25]
### 对问题的清晰和简明的描述

现有的 .gitignore 没有忽略每次一构建时由各种插件生成的文件, 例如: auto-imports.d.ts .
这可能导致 IDE 经常提示文件的换行符不同, 加大开发者提交代码到仓库时需要进行的工作量.

### 推荐的解决方案

建议在现有的 .gitignore 中补充由已经安装的插件生成的文件.

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
不忽略 uni 相关插件生成的文件是因为忽略了冷启动不了了

其他的，我记得 @ModyQyW好像知道原因

**Comment by DevDengChao** [comment]
@KeJunMao 可以参考 Nuxt , 在 postinstall 脚本里执行冷启动所需的准备工作.
