### ISSUE TITLE
打包支付宝小程序运行报错

### ISSUE THREAD

**Issue by DMzmwh** [uni-helper/vitesse-uni-app#28]
### 描述问题

 pnpm run dev:mp-alipay

error[Parse]: d:/qd/vitesse-uni-app/dist/dev/mp-alipay/composables/useQuery.js: Unexpected token
   --> composables\useQuery.js:6:0
  4 |   const query = common_vendor.ref({});
  5 |   common_vendor.onLoad((q) => {
> 6 |     query.value = q ?? {};
  7 |   });
  8 |   const value = common_vendor.computed(() => key ? query.value[common_vendor.unref(key)] : null);
  9 |   return { query, value };

Error: 构建报告不存在: C:\Users\86159\AppData\Local\Temp\minicode_compile_dy\devserver-uLkEzHGjyp-1704158834004

### 复现

当前项目  pnpm run dev:mp-alipay，后运行到支付宝小程序开发者工具就会提示报错

### 系统信息

```Shell
node -v
v18.19.0





Need to install the following packages:
envinfo@7.11.0
Ok to proceed? (y)

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 4.07 GB / 31.37 GB
  Binaries:
    Node: 18.19.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - D:\programfiles\nodejs\node_global\yarn.CMD
    npm: 10.2.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 6.32.1 - D:\programfiles\nodejs\node_global\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Ares-Chang** [comment]
请更新代码，问题已在 #24 修复
