### ISSUE TITLE
能不能出JS版本，真的，太卷了，小项目上TS就是自讨苦吃啊

### ISSUE THREAD

**Issue by tlerbao** [uni-helper/vitesse-uni-app#29]
### 对问题的清晰和简明的描述

现在前端就是卷的，readme里 各种特性单词好像少一个都不够专业一样

要是不标上typescript更是就好像low了一样。

真的，中小项目上TS真的是自讨苦吃，如果再来个全栈一个人，那更是疯了哈哈。

### 推荐的解决方案

希望提供NOTS版本。

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by Ares-Chang** [comment]
这貌似并不是一个问题，怎么使用是项目决定的，如果不想用 ts 可以在 script 中不指定 ts 类型

```vue
<script setup>
console.log(123)
</script>
```

这并不影响使用，只是丢失了 ts 的特性。

各种配置文件的 ts 都可以平替。
