### ISSUE TITLE
Unocss 问题

### ISSUE THREAD

**Issue by Aelanxu** [uni-helper/vitesse-uni-app#38]
### 描述问题

关于 UnoCss的border 属性，只能如下写才能生效，
![image](https://github.com/uni-helper/vitesse-uni-app/assets/8611228/95386e2a-a2a1-4fe0-ae6e-ebd5f6fa8d6e)
如下面写法 就是不生效：
![image](https://github.com/uni-helper/vitesse-uni-app/assets/8611228/aed7a1c0-ab79-4621-ab1c-3e24a49b5972)

### 复现

安装即可

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800U with Radeon Graphics
    Memory: 5.27 GB / 15.31 GB
  Binaries:
    Node: 20.9.0 - C:\devtool\nodejs\node.EXE
    npm: 10.1.0 - C:\devtool\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\devtool\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.59)
    Internet Explorer: 11.0.19041.3636
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Ares-Chang** [comment]
请善用文档，https://unocss.dev/interactive/?s=border-b



![image](https://github.com/uni-helper/vitesse-uni-app/assets/36911513/1080adc2-1fa8-4d80-b11a-eef60206ea54)

**Comment by Ares-Chang** [comment]
border 并未指定线形，可以把鼠标移动到属性上，有下标的为 unocss 可识别属性，它会有提示

**Comment by Aelanxu** [comment]
OK ，我以为和  tailwind 一样呢
