### ISSUE TITLE
unocss 无法智能提示

### ISSUE THREAD

**Issue by Aelanxu** [uni-helper/vitesse-uni-app#39]
### 描述问题

vscode 我反复卸载安装了   unocss插件, 都无法提示！

### 复现

暂无

### 系统信息

```Shell
暂无
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
日志呢

**Comment by KeJunMao** [comment]
没日志的issue以后别提了

**Comment by Aelanxu** [comment]
已经解决了，是配置问题，需要在vite.config.ts 
配置路径：```UnoCSS({
      configFile: './uno.config.ts',
    }),```
要不找不到根目录下的配置文件
不知道为啥我安装的模板配置文件看起来是折叠的图下图：
![image](https://github.com/uni-helper/vitesse-uni-app/assets/8611228/5cee957d-aaa4-4a53-9fd1-d6cbb09d3519)

**Comment by KeJunMao** [comment]
不是，默认就是 uno.config.{js,ts}，你发下你 unocss 扩展的日志才能看出来为啥

**Comment by Aelanxu** [comment]
`🛠 Resolving config for c:\workspace\code\xxxx\urse_in_cloud
🛠 New configuration loaded from
  - c:\workspace\code\xxxxx\nurse_in_cloud\uno.config.ts
ℹ️ 6 presets, 1001 rules, 1 shortcuts, 63 variants, 5 transformers loaded
🗂️ Enabled context: c:\workspace\code\xxxxxx\nurse_in_cloud`
日志感觉没问题
