### ISSUE TITLE
保存的时候自动格式化vue代码

### ISSUE THREAD

**Issue by redwolf1996** [uni-helper/vitesse-uni-app#44]
### 对问题的清晰和简明的描述

![image](https://github.com/uni-helper/vitesse-uni-app/assets/9690393/d7394a28-f0d8-4ee8-8e9d-e9b83f8eb4bb)
目前在vue模板中 template和route标签 保存的时候不能自动格式化, 导致样式凌乱

### 推荐的解决方案

推荐使用eslint的格式化配置格式化 vue template 和 route里的 json  yaml等

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by elkon028** [comment]
安装个依赖即可
```sh
pnpm add -D eslint-plugin-format
```

**Comment by ModyQyW** [comment]
antfu eslint-config 里面默认没有，我们也没有加上，如果有需要可以自己加一下

另外我们打算增加 definePage 支持，可能后续不推荐用 <route> 块了
