### ISSUE TITLE
view、button等原生标签报错

### ISSUE THREAD

**Issue by moke8** [uni-helper/vitesse-uni-app#49]
### 描述问题

`
类型“{}”的参数不能赋给类型“ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<{ readonly onError?: _ButtonOnError | undefined; ... 30 more ...; readonly onAgreeprivacyauthorization?: _ButtonOnAgreeprivacyauthorization | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomPro...”的参数。
  不能将类型“{}”分配给类型“ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<{ readonly onError?: _ButtonOnError | undefined; ... 30 more ...; readonly onAgreeprivacyauthorization?: _ButtonOnAgreeprivacyauthorization | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomPro...”。
    类型“{}”提供的内容与签名“new (...args: any[]): { $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<{ readonly onError?: _ButtonOnError | undefined; ... 30 more ...; readonly onAgreeprivacyauthorization?: _ButtonOnAgreeprivacyauthorization | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...>, never>; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R) => any : (...args: any) => any, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... 5 more ... & {}”不匹配。ts-plugin(2345)
`

div不影响，但是button、input也有问题

### 复现

仅创建与启动项目

### 系统信息

运行 npx create-uni@latest --info 报错
$ npx create-uni@latest --info
⠋ 正在获取插件信息...✖ 操作已取消
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at Ys.setFinishMessage (/Users/mokevip/.npm/_npx/14ac50ce161843f7/node_modules/create-uni/dist/outfile.cjs:2:304989)
    at Ys.fail (/Users/mokevip/.npm/_npx/14ac50ce161843f7/node_modules/create-uni/dist/outfile.cjs:2:305328)
    at el (/Users/mokevip/.npm/_npx/14ac50ce161843f7/node_modules/create-uni/dist/outfile.cjs:2:441152)
    at async tl (/Users/mokevip/.npm/_npx/14ac50ce161843f7/node_modules/create-uni/dist/outfile.cjs:2:442548)
    at async /Users/mokevip/.npm/_npx/14ac50ce161843f7/node_modules/create-uni/dist/outfile.cjs:2:444206
🚀 遇到问题? 快速反馈：https://github.com/uni-helper/create-uni/issues/new/choose

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by FliPPeDround** [comment]
https://github.com/uni-helper/uni-app-types/issues/64
解决方案在上面
你可以再试试`npx create-uni@latest --info`看看还会报错吗？

**Comment by ModyQyW** [comment]
已更新到最新版本，请再尝试一下，由于实在太忙没有及时更新，非常抱歉🙏
