### ISSUE TITLE
eslint不生效

### ISSUE THREAD

**Issue by transtone** [uni-helper/vitesse-uni-app#51]
### 描述问题

![image](https://github.com/uni-helper/vitesse-uni-app/assets/46688/828e1709-fd46-4b87-81ad-6ec657b75d84)
eslint 的规则不生效了。

下面的是非uni-app，缩进提示的效果。

### 复现

用 vscode 打开本项目。

### 系统信息

Need to install the following packages:
create-uni@1.4.3
Ok to proceed? (y) y

(node:2120) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
√ 请选择需要反馈的依赖 » @uni-helper/eslint-config
√ 请选择需要反馈的vscode插件 » uni-highlight-vscode

----------------------------------------------

基础环境信息:
  - os: `Windows 11 10.0.26100`
  - node: `22.2.0`
  - vscode: `1.90.0`
  - volar: `2.0.10`

基础依赖信息:
  - vue: `3.4.27`
  - vite: `5.2.13`
  - @dcloudio/uni-app: `3.0.0-alpha-4000020240111001`

uni-helper依赖信息:
  - @uni-helper/eslint-config: `0.0.6`
    - eslint: `8.57.0`

uni-helper插件信息:
  - uni-highlight-vscode: `0.3.10`

----------------------------------------------
感谢使用uni-helper，请提供以上信息以便我们排查问题。

👉 uni-helper 官网: https://uni-helper.js.org/
👉 改进建议: https://github.com/uni-helper/create-uni/issues/new/choose

### 使用的包管理器

bun

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
依赖已更新，请更新到最新尝试一下，实在太忙了没有及时更新，非常抱歉🙏
