### ISSUE TITLE
有没有办法集成下Vue Macros这个插件

### ISSUE THREAD

**Issue by zhenhappy** [uni-helper/vitesse-uni-app#54]
### 对问题的清晰和简明的描述

由于vue3用了proxy对象，所以每个变量都需要加上.value，所以安装上Vue Macros可以解决这个问题

### 推荐的解决方案

集成Vue Macros插件进来

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
Vue 官方放弃了响应式转换，见 https://github.com/vuejs/rfcs/discussions/369，这个功能不是所有人都想要的，我们不会内置该功能。如果你需要该功能请自行引入。

**Comment by transtone** [comment]
> Vue 官方放弃了响应式转换，见 [https://github.com/vuejs/rfcs/discussions/369，这个功能不是所有人都想要的，我们不会内置该功能。如果你需要该功能请自行引入。](https://github.com/vuejs/rfcs/discussions/369%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%8A%9F%E8%83%BD%E4%B8%8D%E6%98%AF%E6%89%80%E6%9C%89%E4%BA%BA%E9%83%BD%E6%83%B3%E8%A6%81%E7%9A%84%EF%BC%8C%E6%88%91%E4%BB%AC%E4%B8%8D%E4%BC%9A%E5%86%85%E7%BD%AE%E8%AF%A5%E5%8A%9F%E8%83%BD%E3%80%82%E5%A6%82%E6%9E%9C%E4%BD%A0%E9%9C%80%E8%A6%81%E8%AF%A5%E5%8A%9F%E8%83%BD%E8%AF%B7%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E3%80%82)

官方放弃，不代表没有用。不是所有人想要，也不是所有人不想要。

`vite.config.ts`
```js
import VueMacros from 'unplugin-vue-macros/vite'

export default defineConfig({
  plugins: [
    VueMacros({
      plugins: {},
    }),
  // ... 其他配置
],
// ... 其他配置
})
```
