### ISSUE TITLE
每次运行script时manifest.json都会恢复默认

### ISSUE THREAD

**Issue by cecoyu** [uni-helper/vitesse-uni-app#56]
### 描述问题

每次运行pnpm dev:h5或者其他都会使manifest.json的设置恢复默认。比如将h5的darkmode改为false或者删除这个属性，运行pnpm dev:h5后又会恢复默认的设置。

### 复现

运行pnpm dev:h5

### 系统信息

Need to install the following packages:
create-uni@1.5.2
Ok to proceed? (y) 

✔ 获取环境信息成功   

✔ 请选择需要反馈的依赖 › @uni-helper/eslint-config, @uni-helper/uni-env, @uni-helper/uni-types, @uni-helper/unocss-preset-uni, @uni-helper/vite-plugin-uni-components, @uni-helper/vite-plugin-uni-layouts, @uni-helper/vite-plugin-uni-manifest, @uni-helper/vite-plugin-uni-pages, @uni-helper/volar-service-uni-pages
✔ 请选择需要反馈的vscode插件 › uni-app-schemas-vscode, uni-app-snippets-vscode, uni-cloud-snippets-vscode, uni-helper-vscode, uni-highlight-vscode, uni-ui-snippets-vscode

----------------------------------------------

基础环境信息:
  - os: `Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)`
  - node: `21.5.0`
  - packageManager: `pnpm`
  - vscode: `1.93.1`
  - volar: `2.1.6`

基础依赖信息:
  - vue: `3.4.38`
  - vite: `5.4.6`
  - @dcloudio/uni-app: `3.0.0-4020420240722002`

uni-helper依赖信息:
  - @uni-helper/eslint-config: `0.1.0`
    - eslint: `9.10.0`
  - @uni-helper/uni-env: `0.1.4`
  - @uni-helper/uni-types: `1.0.0-alpha.4`
  - @uni-helper/unocss-preset-uni: `0.2.9`
    - unocss: `0.62.4`
  - @uni-helper/vite-plugin-uni-components: `0.1.0`
  - @uni-helper/vite-plugin-uni-layouts: `0.1.10`
  - @uni-helper/vite-plugin-uni-manifest: `0.2.7`
  - @uni-helper/vite-plugin-uni-pages: `0.2.27`
  - @uni-helper/volar-service-uni-pages: `0.2.27`

uni-helper插件信息:
  - uni-app-schemas-vscode: `0.9.3`
  - uni-app-snippets-vscode: `0.10.5`
  - uni-cloud-snippets-vscode: `0.3.0`
  - uni-helper-vscode: `0.5.9`
  - uni-highlight-vscode: `0.3.11`
  - uni-ui-snippets-vscode: `0.6.6`

----------------------------------------------

🎯 感谢使用uni-helper，请提供虚线内的信息以便我们排查问题
   若还需提供其他信息，请自行修改补充

👉 uni-helper 官网: https://uni-helper.js.org/
👉 改进建议: https://github.com/uni-helper/create-uni/issues/new/choose

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by wtto00** [comment]
请修改 `manifest.config.ts` 配置文件，而不是 `manifest.json` 文件

**Comment by LemonOMG** [comment]
修改根目录的 manifest.config.ts 文件，page.json同理
