### ISSUE TITLE
打包app-ios 发现构建文件不全，html页面全都没有

### ISSUE THREAD

**Issue by AursorDev** [uni-helper/vitesse-uni-app#61]
### 描述问题

打包app-ios 发现构建文件不全，html页面全都没有

### 复现

npm run dev:app-ios

### 系统信息

npm run dev:app-ios

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by Ares-Chang** [comment]
参考 [文档](https://uniapp.dcloud.net.cn/quickstart-cli.html#%E5%85%B6%E4%BB%96%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

![image](https://github.com/user-attachments/assets/c984b062-8f4e-4354-beb2-0c69c77a492d)

这个属于 uniapp 硬伤，暂时应该没有别的好方法，如果有欢迎分享
