### ISSUE TITLE
.nvue file support

### ISSUE THREAD

**Issue by Siykt** [uni-helper/vitesse-uni-app#8]
### 对问题的清晰和简明的描述

see https://github.com/zguolee/starter-uni/issues/10

### 推荐的解决方案

主要原因应该是在`eslint-vue-preser`上，目前没有找到合适的解决方案，可能需要`eslint-vue-preser`支持

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
我认为这应该去 `eslint-vue-parser` 提。`.nvue` 并不属于 `vue` 生态内的通用标准，很有可能被驳回支持。

你可以考虑用户侧的 patch，直接修改 `eslint-vue-parser` 的源码来处理，在源码中找到 `".vue"` 并增加 `.nvue` 的判断应该就可以了。

**Comment by Siykt** [comment]
可以通过配置eslint `overrides` 与 `extensions` 实现`.nvue`的支持：

> .eslintrc

```json
{
  "extends": [
    "@antfu",
    "@unocss"
  ],
  "extensions": [".vue", ".nvue"],
  "overrides": [{
    "files": ".nvue",
    "parser": "vue-eslint-parser"
  }]
}
```

**Comment by Siykt** [comment]
参考：https://github.com/mdx-js/eslint-mdx/issues/250#issuecomment-731130966
